In [1]:
import pandas as pd

In [2]:
### bicycle_dup.csv 파일 읽어들이기
# 변수명 : df

file_path = "./data/bicycle_dup.csv"
df = pd.read_csv(file_path, encoding="euc-kr")

df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   자전거번호    420 non-null    object
 1   대여일시     420 non-null    object
 2   대여소번호    420 non-null    int64
 3   대여소명     420 non-null    object
 4   대여거치대    396 non-null    float64
 5   반납일시     420 non-null    object
 6   반납대여소번호  420 non-null    int64
 7   반납대여소명   420 non-null    object
 8   반납거치대    409 non-null    float64
 9   이용시간     405 non-null    float64
 10  이용거리     404 non-null    float64
 11  나이       420 non-null    int64
dtypes: float64(4), int64(3), object(5)
memory usage: 39.5+ KB

,대여소번호,대여거치대,반납대여소번호,반납거치대,이용시간,이용거리,나이
count,420.000000,396.000000,420.000000,409.000000,405.000000,404.000000,420.000000
mean,243.254762,7.585859,93.338095,2.843521,21.185185,2683.465347,35.492857
std,301.148255,6.258985,26.270667,1.699182,20.200058,3025.803402,31.829010
min,3.000000,1.000000,3.000000,1.000000,2.000000,0.000000,21.000000
25%,104.000000,3.000000,101.000000,1.000000,7.000000,1070.000000,24.000000
50%,117.500000,6.000000,101.000000,2.000000,14.000000,1680.000000,29.000000
75%,226.500000,10.000000,101.000000,4.000000,27.000000,3757.500000,40.000000
max,3102.000000,30.000000,101.000000,7.000000,122.000000,42070.000000,533.000000

## 결측치 처리

In [ ]:
### 결측치가 있는 컬럼들은 대체하기
# - 각 컬럼의 [전체 평균값]으로 대체하기
# - 결측치가 있는 컬럼 : 대여거치대, 반납거치대, 이용시간, 이용거리

In [3]:
### 각각 처리 코드
df["대여거치대"].fillna(df["대여거치대"].mean())
df["반납거치대"].fillna(df["반납거치대"].mean())
df["이용시간"].fillna(df["대여거치대"].mean())
df["이용거리"].fillna(df["이용거리"].mean())

### 응용처리
cols = ["대여거치대", "반납거치대", "이용시간", "이용거리"]
for col in cols :
    df[col].fillna(df[col].mean())

### 간단처리
df.fillna(df[["대여거치대", "반납거치대", "이용시간", "이용거리"]].mean())

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.000000,12.0,1100.000000,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.000000,7.0,1100.000000,50
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.000000,10.0,2683.465347,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,2.843521,10.0,1380.000000,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.000000,10.0,1650.000000,120
...,...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.000000,11.0,2200.000000,22
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,2.843521,5.0,2683.465347,22
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.000000,12.0,2280.000000,37
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.000000,10.0,1180.000000,27
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.000000,48.0,8100.000000,28

In [4]:
df = df.fillna(df[["대여거치대", "반납거치대", "이용시간", "이용거리"]].mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   자전거번호    420 non-null    object
 1   대여일시     420 non-null    object
 2   대여소번호    420 non-null    int64
 3   대여소명     420 non-null    object
 4   대여거치대    420 non-null    float64
 5   반납일시     420 non-null    object
 6   반납대여소번호  420 non-null    int64
 7   반납대여소명   420 non-null    object
 8   반납거치대    420 non-null    float64
 9   이용시간     420 non-null    float64
 10  이용거리     420 non-null    float64
 11  나이       420 non-null    int64
dtypes: float64(4), int64(3), object(5)
memory usage: 39.5+ KB

## 전체 행단위 중복 데이터 확인하기

In [5]:
### duplicated() : 중복 체크 함수
# - 중복이 있는 부분은 True, 없는 부분은 False
df.duplicated()

### 중복이 있는 True의 총갯수와 중복이 없는 False의 총갯수 확인하기
df.duplicated().value_counts()

False    420
Name: count, dtype: int64

## 특정 컬럼을 기준으로 행단위 중복확인

In [8]:
### 이용거리 컬럼을 기준으로 중복 확인
# - 중복 데이터 중에 첫번째 중복값은 False,
#                  두번째 이상 중복값들은 모두 True가 됩니다.
# - 중복값 중 에 하나는 존재해야하기 때문에...
df["이용거리"]

0      1100.000000
1      1100.000000
2      2683.465347
3      1380.000000
4      1650.000000
          ...
415    2200.000000
416    2683.465347
417    2280.000000
418    1180.000000
419    8100.000000
Name: 이용거리, Length: 420, dtype: float64

In [9]:
df["이용거리"].duplicated()
df.duplicated(["이용거리"])

0      False
1       True
2      False
3      False
4      False
       ...
415    False
416     True
417     True
418     True
419    False
Length: 420, dtype: bool

In [ ]:
### 이용거리 컬럼을 기준으로 중복 확인
# - 이용거리 컬럼에서 중복이 없는, 중복이 없는 모든 컬럼의 데이터 조회해 주세요

In [16]:
c = df.duplicated(["이용거리"])
df[c == False]

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.000000,12.0,1100.000000,50
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.000000,10.0,2683.465347,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,2.843521,10.0,1380.000000,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.000000,10.0,1650.000000,120
5,SPB-18401,2019-11-06 8:52,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:09,3,중랑센터,7.000000,11.0,1350.000000,30
...,...,...,...,...,...,...,...,...,...,...,...,...
410,SPB-18614,2019-11-14 23:07,391,정동길입구,5.0,2019-11-14 23:49,101,(구)합정동 주민센터,3.000000,40.0,7510.000000,28
413,SPB-25161,2019-11-15 3:13,106,합정역 7번출구 앞,6.0,2019-11-15 3:18,101,(구)합정동 주민센터,1.000000,3.0,640.000000,21
414,SPB-24515,2019-11-15 3:58,112,극동방송국 앞,1.0,2019-11-15 4:08,101,(구)합정동 주민센터,1.000000,9.0,1620.000000,21
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.000000,11.0,2200.000000,22
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.000000,48.0,8100.000000,28

## 중복값 선택하기

In [20]:
### keep : 중복에서 제외할 위치 지정
# - first : 첫번째 중복값은 중복에서 제외(첫번째 이후 부터는 중복 처리)
#         : 기본값은 생략가능
# - last : 마지막 중복값은 중복에서 제외(마지막 이전 데이터는 모두 중복 처리)
# - False : 모두 중복 처리
df.duplicated(["이용거리"], keep = "first")

0      False
1       True
2      False
3      False
4      False
       ...
415    False
416     True
417     True
418     True
419    False
Length: 420, dtype: bool

In [21]:
df.duplicated(["이용거리"], keep = "last")

0       True
1       True
2       True
3       True
4      False
       ...
415    False
416    False
417    False
418    False
419    False
Length: 420, dtype: bool

In [23]:
df.duplicated(["이용거리"], keep = False)

0       True
1       True
2       True
3       True
4      False
       ...
415    False
416     True
417     True
418     True
419    False
Length: 420, dtype: bool

## 중복데이터 처리하기

In [ ]:
"""
<중복데이터 처리 방법>
 1. 중복값 확인
  - 중복을 허용하는 데이터인지 확인 필요(데이터를 제공해 주시분들에게)
 2. 중복값을 삭제할지, 그냥 사용할지 결정
  * 삭제할 경우
   -> 중복된 행을 삭제합니다.
  * 그냥 사용할 경우
   -> 실제로 중복이 가능한 데이터의 성격인 경우가 해당됩니다.
"""

In [24]:
### 중복 데이터 삭제하기
# - 행 단위 삭제가 진행됩니다.

### 행 전체 중복이 있는 경우, 해당 행 삭제
# - 단 keep의 중복 위치 조건에 따라 True인 행만 삭제
df.drop_duplicates(keep="first")

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.000000,12.0,1100.000000,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.000000,7.0,1100.000000,50
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.000000,10.0,2683.465347,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,2.843521,10.0,1380.000000,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.000000,10.0,1650.000000,120
...,...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.000000,11.0,2200.000000,22
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,2.843521,5.0,2683.465347,22
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.000000,12.0,2280.000000,37
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.000000,10.0,1180.000000,27
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.000000,48.0,8100.000000,28

In [31]:
### 이용거리 컬럼 데이터를 기준으로 중복된 행 삭제하기
# - 최초 중복은 중복에서 제외하기
df["이용거리"].drop_duplicates(keep="first")

### 중복 제거 후에 데이터를 다시 가지고 와야하기에, 아래 방법이 편한 방법이 될 수 있음
df.drop_duplicates(["이용거리"], keep="first")

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.000000,12.0,1100.000000,50
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.000000,10.0,2683.465347,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,2.843521,10.0,1380.000000,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.000000,10.0,1650.000000,120
5,SPB-18401,2019-11-06 8:52,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:09,3,중랑센터,7.000000,11.0,1350.000000,30
...,...,...,...,...,...,...,...,...,...,...,...,...
410,SPB-18614,2019-11-14 23:07,391,정동길입구,5.0,2019-11-14 23:49,101,(구)합정동 주민센터,3.000000,40.0,7510.000000,28
413,SPB-25161,2019-11-15 3:13,106,합정역 7번출구 앞,6.0,2019-11-15 3:18,101,(구)합정동 주민센터,1.000000,3.0,640.000000,21
414,SPB-24515,2019-11-15 3:58,112,극동방송국 앞,1.0,2019-11-15 4:08,101,(구)합정동 주민센터,1.000000,9.0,1620.000000,21
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.000000,11.0,2200.000000,22
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.000000,48.0,8100.000000,28

In [ ]:
.apply(lambda x : 1 if x == "Male" else 0)